version: '2.1'

networks:
  app-tier:
    driver: bridge

services:
      mysql:
        image: mysql:5.7
        container_name: msql-server
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Abc123456!
        ports:
          - 8889:3306
        networks:
          - app-tier
        healthcheck:
          test: "exit 0"
      redis:
        image: bitnami/redis:latest
        container_name: redis-server
        restart: always
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - 6379:6379
        networks:
          - app-tier
        healthcheck:
          test: "exit 0"
      api:
        # build: .
        image: minhlt/jhapi:v1
        container_name: jh-api
        ports:
          - 8888:80
        depends_on:
          mysql:
            condition: service_healthy
          redis:
            condition: service_healthy
        networks:
          - app-tier
      
