version: '2.1'

networks:
  app-tier: 
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
services:
      redis:
        image: bitnami/redis:latest
        container_name: jh-redis-server
        restart: always
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        ports:
          - 6379:6379
        networks:
          app-tier:
            ipv4_address: 172.19.0.11
        healthcheck:
          test: "exit 0"
      mysql:
        image: mysql:5.7
        container_name: jh-msql-server
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: Abc123456!
        ports:
          - 8889:3306
        networks:
          app-tier:
            ipv4_address: 172.19.0.10
        healthcheck:
          test: "exit 0"
      api:
        # build: .
        image: minhlt/jhapi:v2.4
        container_name: jh-api
        ports:
          - 8888:80
        depends_on:
          mysql:
            condition: service_healthy
          redis:
            condition: service_healthy
        networks:
          app-tier:
            ipv4_address: 172.19.0.5
      
